/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unidf.UI;

import br.unidf.DAL.ContatoDAL;
import br.unidf.DTO.ContatoDTO;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 *
 */
public class frmContatos extends javax.swing.JFrame {

    /**
     * Creates new form frmContatos
     */
    public frmContatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btnIncluirCon = new javax.swing.JButton();
        ftfTelefoneCon = new javax.swing.JFormattedTextField();
        btnAlterarCon = new javax.swing.JButton();
        btnExcluirCon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarTodosCon = new javax.swing.JButton();
        txtCodigoIDCon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvContatos = new javax.swing.JTable();
        btnLimparCon = new javax.swing.JButton();
        btnPesquisarConID = new javax.swing.JButton();
        btnSairCon = new javax.swing.JButton();
        txtNomeCon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Contatos");
        setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        setResizable(false);

        jLabel8.setText("Telefone");

        btnIncluirCon.setMnemonic('I');
        btnIncluirCon.setText("Incluir");
        btnIncluirCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirConActionPerformed(evt);
            }
        });

        try {
            ftfTelefoneCon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAlterarCon.setMnemonic('A');
        btnAlterarCon.setText("Alterar");
        btnAlterarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarConActionPerformed(evt);
            }
        });

        btnExcluirCon.setMnemonic('E');
        btnExcluirCon.setText("Excluir");
        btnExcluirCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirConActionPerformed(evt);
            }
        });

        jLabel2.setText("Código(ID)");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Cadastro de Contatos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(333, 333, 333))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        btnMostrarTodosCon.setMnemonic('M');
        btnMostrarTodosCon.setText("Mostrar Todos");
        btnMostrarTodosCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosConActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do Contato");

        dgvContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código (ID)", "Nome", "Telefone"
            }
        ));
        dgvContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvContatos);

        btnLimparCon.setMnemonic('L');
        btnLimparCon.setText("Limpar");
        btnLimparCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparConActionPerformed(evt);
            }
        });

        btnPesquisarConID.setMnemonic('P');
        btnPesquisarConID.setText("Pesquisar");
        btnPesquisarConID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarConIDActionPerformed(evt);
            }
        });

        btnSairCon.setMnemonic('S');
        btnSairCon.setText("Sair");
        btnSairCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoIDCon, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarConID)
                                .addGap(0, 765, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNomeCon))
                        .addGap(145, 145, 145))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnIncluirCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterarCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarTodosCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimparCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSairCon))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ftfTelefoneCon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoIDCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarConID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftfTelefoneCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirCon)
                    .addComponent(btnAlterarCon)
                    .addComponent(btnExcluirCon)
                    .addComponent(btnMostrarTodosCon)
                    .addComponent(btnLimparCon)
                    .addComponent(btnSairCon))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirConActionPerformed
        //Abrindo a conexão com o Banco de Dados
        ContatoDAL dal = new ContatoDAL();
        try
        {
            dal.abrirBD();
        }
        catch (Exception ex)
        {
            Logger.getLogger(frmContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        // instanciando a classe ContatoDTO do pacote DTO e criando seu objeto contato
        ContatoDTO conatato = new ContatoDTO();
        contato.setConNome(txtNomeCon.getText());
        contato.setConTel(ftfTelefoneCon.getText());
        // fazendo a validação dos dados
        if ((txtNomeCon.getText().isEmpty()) || (ftfTelefoneCon.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Os campos não podem estar vazios !!!!");
            txtNomeCon.requestFocus();
        }
        else
        {
            try {
                // Instancia a classe ContatoDAL e chama o método incluirContato
                dal.incluirContato(contato);
                JOptionPane.showMessageDialog(null, "Usuário " + txtNomeCon.getText() + " incluído com sucesso! ");
                dal.fecharBD();
                txtNomeCon.requestFocus();
                btnMostrarTodosCon.setEnabled(true);
            } catch (Exception ex)
            {
                Logger.getLogger(frmContatos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // apaga os dados preenchidos nos campos de texto
        txtCodigoIDCon.setText("");
        txtNomeCon.setText("");
        ftfTelefoneCon.setText(null);

    }//GEN-LAST:event_btnIncluirConActionPerformed

    private void btnSairConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairConActionPerformed
        // Fecha o formulário de contatos e volta para o formulário principal
        dispose();

    }//GEN-LAST:event_btnSairConActionPerformed

    private void btnAlterarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarConActionPerformed
        // fazendo a validação dos dados, o método isEmpty que devolve true se a String for vazia ou false se a mesma nã estiver vazia
        if ((txtNomeCon.getText().isEmpty()) || (ftfTelefoneCon.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Verifique Se Tem Algum Campo Vazio !!!!");
            //O cursor do mouse vai se posicionado no campo Código do Contato
            txtCodigoIDCon.requestFocus();
        }
        else 
        {
            // instanciando a classe ContatosDTO do pacote DTO e criando seu objeto contato
            ContatoDTO contato = new ContatoDTO();
            // Instancia a classe ContatoDAL 
            ContatoDAL dal = new ContatoDAL();
            contato.setConID(Long.parseLong(txtCodigoIDCon.getText()));
            contato.setConNome(txtNomeCon.getText());
            //Mostra os dados que estão gravados na tabela Contatos
            contato.setConTel(ftfTelefoneCon.getText());
            try
            {
                // Chama o método alterarContato da Classe ContatoDAL
                dal.alterarContato(contato);
            }
            catch (Exception ex)
            {
                Logger.getLogger(frmContatos.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Contato " + contato.getConNome() + " Alterado Com Sucesso !!!!");
        }

    }//GEN-LAST:event_btnAlterarConActionPerformed

    private void btnExcluirConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirConActionPerformed
        //Verifica se os campos estão preenchidos    
        if (((txtNomeCon.getText().isEmpty()) || (ftfTelefoneCon.getText().isEmpty()) || (txtCodigoIDCon.getText().isEmpty()))) {
            JOptionPane.showMessageDialog(null, "Verifique Se Tem Algum Campo Vazio !!!!");
            txtCodigoIDCon.requestFocus();
        }
        else
        {
            // instanciando a classe contatosDTO do pacote DTO e criando seu objeto contato        
            ContatoDTO contato = new ContatoDTO();
            contato.setConID(Long.parseLong(txtCodigoIDCon.getText()));
            Object[] opcoes = {"Sim", "Não"};
            int contador = JOptionPane.showOptionDialog(null, "Deseja Excluir Este Contato: " + txtNomeCon.getText() + "?",
                    "Exclusão", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
            if (contador == JOptionPane.YES_OPTION) {
                try
                {
                    ContatoDAL dal = new ContatoDAL();
                    dal.excluirContato(Integer.valueOf(txtCodigoIDCon.getText()));
                    JOptionPane.showMessageDialog(null, "Contato Excluído com Sucesso !!!!");
                    // apaga os dados preenchidos nos campos de texto abaixo
                    txtCodigoIDCon.setText(null);
                    txtNomeCon.setText("");
                    ftfTelefoneCon.setText(null);
                    txtCodigoIDCon.requestFocus();
                }
                catch (Exception ex)
                {
                    Logger.getLogger(frmContatos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnExcluirConActionPerformed

    private void btnMostrarTodosConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosConActionPerformed
        //Limpa todas as caixas de texto
        txtCodigoIDCon.setText("");
        txtNomeCon.setText("");
        ftfTelefoneCon.setText(null);
        // instanciando a classe contatosDAL
        ContatoDAL contato = new ContatoDAL();
        //Cria a lista de todos os contatos dentro da tabela Contatos
        List<ContatoDTO> selecionaTodosConentes = new ArrayList<>();
        try
        {
            //Chama o método selecionaTodosContatos da Classe ContatosDAL e preeche
            //o mesmo com a lista de todos os contatops.
            selecionaTodosContatos = contato.selecionarListaContatos();
        }
        catch (Exception ex)
        {
            Logger.getLogger(frmContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Prepara a tabela para receber os dados da busca(Lista)
        DefaultTableModel tabm = (DefaultTableModel)dgvContatos.getModel();
        for(int contador = tabm.getRowCount()-1; contador >=0; contador--)
        {
            tabm.removeRow(contador);
        }
        int contador = 0;
        for(ContatoDTO conatatos : selecionaTodosContatos)
        {
            //Mostra as informações dentro da Tabela
            tabm.addRow(new String[1]);
            dgvContatos.setValueAt(contatos.getConID(), contador, 0);
            dgvCcontatos.setValueAt(contatos.getConNome(),contador, 1);
            dgvContatos.setValueAt(contatos.getConTel(), contador, 2);        
            contador++;
        }
        //Limpa o campo Código do Contato
        txtCodigoIDCon.setText(null);
        //Posiciona o cursor do mouse no campo Nome do contato
        txtNomeCon.requestFocus();

    }//GEN-LAST:event_btnMostrarTodosConActionPerformed

    private void btnLimparConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparConActionPerformed
        //Limpa os campos do formulário e do grid ou tabela 
        btnIncluirCon.setEnabled(true);
        btnAlterarCon.setEnabled(false);
        btnExcluirCon.setEnabled(false);
        btnMostrarTodosCon.setEnabled(true);
        txtCodigoIDCon.setText("");
        txtNomeCon.setText("");
        ftfTelefoneCon.setText(null);
        txtNomeCon.requestFocus();
        DefaultTableModel tabm = (DefaultTableModel)dgvContatos.getModel();
        for (int contador = tabm.getRowCount() -1; contador >= 0; contador--)
        {
            tabm.removeRow(contador);
        }

    }//GEN-LAST:event_btnLimparConActionPerformed

    private void btnPesquisarConIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarConIDActionPerformed
        //Verifica se o código do contato está vazio
        if ("".equals(txtCodigoIDCon.getText()))
        {
            JOptionPane.showMessageDialog(null, "Código do Contato não pode ser vazio, favor digite um código válido !!!!");
            //Após a mensagem de erro, o foco do cursor vai ficar no campo Código do Contato
            txtCodigoIDCon.requestFocus();
        }
        else
        {
            //Faz o tratamento de erro, para verificar se a tabela Contatos está vazia
            try
            {
                // instanciando a classe ContatoDTO do pacote DTO e criando seu objeto contato
                ContatoDTO contato = new ContatoDTO();
                // Instancia a classe ContatosDAL
                ContatoDAL dal = new ContatoDAL();
                //Formatando a data para ser exibida no formato Brasileiro
                contato = dal.selecionarContatoPorID(Integer.valueOf(txtCodigoIDCon.getText()));
                //O botão Incluir vai ficar dsesabilitado
                btnIncluirCon.setEnabled(false);
                //O botão Alterar vai ficar habilitado
                btnAlterarCon.setEnabled(true);
                //O botão Excluir vai ficar habilitado
                btnExcluirCon.setEnabled(true);
                //O botão Mostrar Todos vai ficar habilitado
                btnMostrarTodosCon.setEnabled(true);
                //Mostra os dados do Contato pelo seu código
                txtNomeCon.setText(contato.getConNome());
                //Formatando a data do banco, para localdate
                ftfTelefoneCon.setText(contato.getConTel());
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Contato Não Encontrado. Favor Tente Novamente !!!!");
                txtCodigoIDCon.setText(null);
                txtCodigoIDCon.requestFocus();
            }
        }

    }//GEN-LAST:event_btnPesquisarConIDActionPerformed

    private void dgvContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvContatosMouseClicked
         // Preenche o Grid com os dados gravados na tabela contatos do MySQL
        //Formatando a data do banco, para localdate
        int linhaSelecionada = dgvContatos.getSelectedRow();
        txtCodigoIDCon.setText(dgvCcontatos.getValueAt(linhaSelecionada, 0).toString());
        txtNomeCon.setText(dgvContatos.getValueAt(linhaSelecionada, 1).toString());
        ftfTelefoneCon.setText(dgvContatos.getValueAt(linhaSelecionada, 2).toString());
        btnIncluirCon.setEnabled(false);
        btnAlterarCon.setEnabled(true);
        btnExcluirCon.setEnabled(true);

    }//GEN-LAST:event_dgvContatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmContatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCon;
    private javax.swing.JButton btnExcluirCon;
    private javax.swing.JButton btnIncluirCon;
    private javax.swing.JButton btnLimparCon;
    private javax.swing.JButton btnMostrarTodosCon;
    private javax.swing.JButton btnPesquisarConID;
    private javax.swing.JButton btnSairCon;
    private javax.swing.JTable dgvContatos;
    private javax.swing.JFormattedTextField ftfTelefoneCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigoIDCon;
    private javax.swing.JTextField txtNomeCon;
    // End of variables declaration//GEN-END:variables
}
